tailwind.config = {
    darkMode: "class",
    theme: {
        extend: {
            "colors": {
                "on-secondary-fixed-variant": "#324575",
                "on-surface-variant": "#424654",
                "surface-dim": "#d9dadb",
                "on-primary-fixed": "#001847",
                "tertiary-fixed": "#ffdbcf",
                "surface-container": "#edeeef",
                "secondary-fixed-dim": "#b3c5fd",
                "on-tertiary-container": "#ffcebd",
                "primary-container": "#0056d2",
                "on-primary": "#ffffff",
                "on-error": "#ffffff",
                "on-error-container": "#93000a",
                "on-tertiary-fixed": "#380d00",
                "surface-container-highest": "#e1e3e4",
                "on-tertiary-fixed-variant": "#812800",
                "error": "#ba1a1a",
                "on-surface": "#191c1d",
                "on-primary-fixed-variant": "#0040a1",
                "surface-bright": "#f8f9fa",
                "surface": "#f8f9fa",
                "secondary-container": "#b3c5fd",
                "on-tertiary": "#ffffff",
                "inverse-surface": "#2e3132",
                "secondary": "#4a5d8e",
                "inverse-primary": "#b2c5ff",
                "surface-container-lowest": "#ffffff",
                "secondary-fixed": "#dae2ff",
                "background": "#f8f9fa",
                "tertiary-container": "#a93802",
                "surface-container-low": "#f3f4f5",
                "error-container": "#ffdad6",
                "on-secondary-fixed": "#001847",
                "outline": "#737785",
                "primary-fixed": "#dae2ff",
                "surface-container-high": "#e7e8e9",
                "primary-fixed-dim": "#b2c5ff",
                "inverse-on-surface": "#f0f1f2",
                "surface-tint": "#0056d2",
                "tertiary-fixed-dim": "#ffb59b",
                "outline-variant": "#c3c6d6",
                "on-primary-container": "#ccd8ff",
                "primary": "#0040a1",
                "on-secondary": "#ffffff",
                "tertiary": "#822800",
                "on-background": "#191c1d",
                "surface-variant": "#e1e3e4",
                "on-secondary-container": "#3e5181"
            },
            "borderRadius": {
                "DEFAULT": "0.5rem",
                "lg": "1rem",
                "xl": "1.25rem",
                "full": "9999px"
            },
            "fontFamily": {
                "headline": ["Manrope", "sans-serif"],
                "body": ["Inter", "sans-serif"],
                "label": ["Inter", "sans-serif"]
            }
        },
    },
}
